version: 0.2

phases:
  install:
    commands:
      - choco feature enable -n allowGlobalConfirmation
      # install Node
      - cinst nodejs
      # install Yarn
      - choco install yarn
  
  pre_build:
    commands:
      # install dependencies
      - yarn install
  
  build:
    commands:
      # tests

      # builds
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build